### ISSUE TITLE
【依頼】フリマアプリ挙動確認

### ISSUE THREAD

**Issue by Yoppippi** [Yoppippi/furima_28873#11]
自身のフリマアプリのURL：https://furima-28873.herokuapp.com/
Basic認証のIDとパスワード：ID : admin     Password : 0000
出品者用のメールアドレスとパスワード：メールアドレス : minato@sample   パスワード : aa123456
購入者用のメールアドレスとパスワード：メールアドレス : kanade@sample   パスワード : aa123456
購入用カードの番号・期限・セキュリティコード：番号 : 4242424242424242   期限 : 12/24   セキュリティコード : 123

**Comment by tech-taro** [comment]
Yoppippiさん、ご提出ありがとうございます！
挙動確認させて頂きましたが、完成要件は全く問題ございませんでしたのでLGTMとさせて頂きます🎉
おめでとうございます！


必須ではありませんが、余裕があればこちらも修正し、よりクオリティの高いアプリケーションにしてみていただければと思います。
よりよいアプリにすべく以下の点を修正お願いします！
・商品削除機能の確認
購入済みの商品を削除しようとするとエラーになる


**※確認したのは必須機能のみで追加実装した機能については確認していません。
そのため追加機能を実装している場合は、正しく想定通りの挙動であるかご自身で再度確認をお願いいたします。**

**Comment by Yoppippi** [comment]
ありがとうございます！
